#!/bin/bash

#* LIBRARY Holds constants for colors

#* Const LIB_COLOR_NOCOLOR Resets color to default
LIB_COLOR_NOCOLOR='\033[0m'
#* Const LIB_COLOR_BLACK Black
LIB_COLOR_BLACK='\033[0;30m'
#* Const LIB_COLOR_RED Red
LIB_COLOR_RED='\033[0;31m'
#* Const LIB_COLOR_GREEN Green
LIB_COLOR_GREEN='\033[0;32m'
#* Const LIB_COLOR_ORANGE Orange (same as brown)
LIB_COLOR_ORANGE='\033[0;33m'
#* Const LIB_COLOR_BROWN Brown (same as orange)
LIB_COLOR_BROWN='\033[0;33m'
#* Const LIB_COLOR_BLUE Blue
LIB_COLOR_BLUE='\033[0;34m'
#* Const LIB_COLOR_PURPLE Purple
LIB_COLOR_PURPLE='\033[0;35m'
#* Const LIB_COLOR_CYAN Cyan
LIB_COLOR_CYAN='\033[0;36m'
#* Const LIB_COLOR_LIGHTGRAY Light gray
LIB_COLOR_LIGHTGRAY='\033[0;37m'
#* Const LIB_COLOR_DARKGRAY Dark gray
LIB_COLOR_DARKGRAY='\033[1;30m'
#* Const LIB_COLOR_LIGHTRED Light red
LIB_COLOR_LIGHTRED='\033[1;31m'
#* Const LIB_COLOR_LIGHTGREEN Light green
LIB_COLOR_LIGHTGREEN='\033[1;32m'
#* Const LIB_COLOR_YELLOW Yellow
LIB_COLOR_YELLOW='\033[1;33m'
#* Const LIB_COLOR_LIGHTBLUE Light blue
LIB_COLOR_LIGHTBLUE='\033[1;34m'
#* Const LIB_COLOR_LIGHTPURPLE Light purple
LIB_COLOR_LIGHTPURPLE='\033[1;35m'
#* Const LIB_COLOR_LIGHTCYAN Light cyan
LIB_COLOR_LIGHTCYAN='\033[1;36m'
#* Const LIB_COLOR_WHITE White
LIB_COLOR_WHITE='\033[1;37m'

#* Const LIB_BGCOLOR_NOCOLOR Resets color to default
LIB_BGCOLOR_NOCLOR=
